### ISSUE TITLE
レポジトリのdescriptionについて

### ISSUE THREAD

**Issue by Sotalbireo** [MysticDoll/SlackPallete#4]
どうせ`http://mysticdoll.com/SlackPallete/`にリダイレクトされてしまうのであれば、最初から`http://mysticdoll.com/SlackPallete/`にリンクしておいた方が優しいのではないかと思いました。
ご一考ください。

**Comment by MysticDoll** [comment]
あれ、普通にhttp://mysticdoll.com/SlackPallete にしてないですかね
一応www.の方がCNAMEで通ってて、VPS経由でmysticdoll.com/の方にreturnしている形ですね

**Comment by Sotalbireo** [comment]
あっごめんなさい言葉足らずでした。
リンクはhttp://mysticdoll.com/SlackPallete に貼ってあると思うんですが、実際に飛んだ後のURLってhttp://mysticdoll.com/SlackPallete/ っぽいんですよ（末尾に`/`が入る）。
なので、最初から`/`入ってた方が良いのかなー、と。

**Comment by MysticDoll** [comment]
あーなるほど、それは普通にGitHub Pagesがtrailing slashを勝手に補完してくれてるから何も考えてなかったですね。一応trailing slash追加しておきますね
